### ISSUE TITLE
CRuby 3.0.2 cannot run bundle install with fresh rails 6 project

### ISSUE THREAD

**Issue by tjarratt** [ruby/setup-ruby#213]
I created a brand new rails 6.1.4.1 project with CRuby 3.0.2, and a minimal github action workflow and ran head-first into a very strange error. My CI runs consistently result in the same error during the `bundle install` step on `x86_64-linux`. I am not using self-hosted runners, just github's own linux machines.

```
NoMethodError: undefined method `full_name' for nil:NilClass
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:124:in `block (2 levels) in check_for_unmet_dependencies'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:123:in `each'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:123:in `block in check_for_unmet_dependencies'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:122:in `each'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:122:in `check_for_unmet_dependencies'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:100:in `call'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:71:in `call'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer.rb:263:in `install_in_parallel'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer.rb:210:in `install'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer.rb:90:in `block in run'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/process_lock.rb:12:in `block in lock'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/process_lock.rb:9:in `open'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/process_lock.rb:9:in `lock'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer.rb:72:in `run'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/installer.rb:24:in `install'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli/install.rb:60:in `run'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli.rb:252:in `block in install'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/settings.rb:131:in `temporary'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli.rb:251:in `install'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli.rb:31:in `dispatch'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli.rb:25:in `start'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/exe/bundle:49:in `block in <top (required)>'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/exe/bundle:37:in `<top (required)>'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `load'
  /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `<main>'
```

Git Repo: https://github.com/tjarratt/scrum-didly-testing
Failed GH action run logs : https://github.com/tjarratt/scrum-didly-testing/runs/3457587536?check_suite_focus=true

Once I had downgraded to CRuby 2.7.4 I observed that `bundle install` succeeds.

Successful GH action run logs : https://github.com/tjarratt/scrum-didly-testing/runs/3457618864?check_suite_focus=true

**Comment by eregon** [comment]
Could you try locally if you see the same error with 3.0.2?

**Comment by tjarratt** [comment]
Hello @eregon I would be happy to, but I didn't see any obvious instructions in the `README` for how to try this locally. I peered into the code, but the high level steps were a bit obscured by some of the error handling.

Is this documented somewhere ? If not, if you can point me in the right direction I'd be happy to write that documentation...

**Comment by eregon** [comment]
Just following the commands in the log should be enough.
https://raw.githubusercontent.com/ruby/setup-ruby/master/.github/ISSUE_TEMPLATE/bug_report.md says:
> * Try to reproduce the issue locally by following the workflow steps (including all commands done by ruby/setup-ruby, except for `Downloading Ruby` & `Extracting Ruby`). If it does reproduce locally, it's not a ruby/setup-ruby issue.

**Comment by eregon** [comment]
BTW this seems to be clearly a Bundler or RubyGems issue (and not related to this action), so best to report at https://github.com/rubygems/rubygems

**Comment by eregon** [comment]
Also https://github.com/tjarratt/scrum-didly-testing/runs/3457587536?check_suite_focus=true#step:4:556 clearly says to report to Bundler
