### ISSUE TITLE
Unsupported platform while running on self-hosted macos-11

### ISSUE THREAD

**Issue by wdjunaidi** [ruby/setup-ruby#335]
We got the following error recently when running on self-hosted macos-11; while it was working in the past:

```
> Run ruby/setup-ruby@v1
Using 2.7.6 as input from file .ruby-version
Error: Error: Unsupported platform macos-11.61
    at Module.getAvailableVersions (/Users/sirminibuildalot/.farmiq-ci/fastlane-2.284/_work/_actions/ruby/setup-ruby/v1/dist/index.js:59580:11)
    at setupRuby (/Users/sirminibuildalot/.farmiq-ci/fastlane-2.284/_work/_actions/ruby/setup-ruby/v1/dist/index.js:60350:36)
    at run (/Users/sirminibuildalot/.farmiq-ci/fastlane-2.284/_work/_actions/ruby/setup-ruby/v1/dist/index.js:60323:11)
    at /Users/sirminibuildalot/.farmiq-ci/fastlane-2.284/_work/_actions/ruby/setup-ruby/v1/dist/index.js:60485:40
    at /Users/sirminibuildalot/.farmiq-ci/fastlane-2.284/_work/_actions/ruby/setup-ruby/v1/dist/index.js:60487:3
    at Object.<anonymous> (/Users/sirminibuildalot/.farmiq-ci/fastlane-2.284/_work/_actions/ruby/setup-ruby/v1/dist/index.js:60490:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:[14](https://github.com/FarmIQSystemsLimited/FarmIQ/runs/6444092661?check_suite_focus=true#step:5:14))
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1[15](https://github.com/FarmIQSystemsLimited/FarmIQ/runs/6444092661?check_suite_focus=true#step:5:15)3:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:8[22](https://github.com/FarmIQSystemsLimited/FarmIQ/runs/6444092661?check_suite_focus=true#step:5:22):12)
```

The version on the self-hosted box:
```
> sw_vers
ProductName:	macOS
ProductVersion:	11.6.5
BuildVersion:	20G527
```

`ruby/setup-ruby`'s README said it should support what GitHub Hosted Runners supports. According to https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md , GitHub Hosted Runner is running _11.6.5_.

Looking at the code, it seems `ruby/setup-ruby` is doing a hard check that it must match to `macos-11.0`.

**Comment by MSP-Greg** [comment]
What is the value of `ENV['ImageOS']` on your runner?

**Comment by wdjunaidi** [comment]
You are right, our is set to `macos1161`. Change it to `macos11` and it is working now.
