### ISSUE TITLE
Bundle failed with exit code null

### ISSUE THREAD

**Issue by andychongyz** [ruby/setup-ruby#351]
Hi people, I need some help to debug why the bundling step failed, and no exit code. The log seems like it actually bundles successfully.

- Using a self-hosted runner

Failed step:
```yml
      - name: Setup Ruby, bundle & cache Ruby gems
        env:
          RAILS_ENV: test
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
```

Log:
```bash
  /opt/hostedtoolcache/Ruby/3.0.3/x64/bin/bundle config --local path /root/actions-runner/_work/project-tapir/project-tapir/vendor/bundle
  /opt/hostedtoolcache/Ruby/3.0.3/x64/bin/bundle config --local deployment true
  Cache key: setup-ruby-bundler-cache-v3-ubuntu-20.04-ruby-3.0.3-cachever:1-Gemfile.lock-d5b991f4f2d29c77fa3939b0ff411c89d3961c23e8d59b21c4477a48d95ecaa3
  /opt/hostedtoolcache/Ruby/3.0.3/x64/bin/bundle install --jobs 4
  Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
  Fetching gem metadata from https://rubygems.org/.......
  Fetching https://github.com/customerio/customerio-ruby
  Fetching https://github.com/andychongyz/scout_apm_ruby.git
  Fetching https://github.com/ondrejbartas/sidekiq-cron.git
  Fetching rake 13.0.6
  Installing rake 13.0.6
  Fetching Ascii85 1.1.0
  Fetching minitest 5.15.0
  Fetching zeitwerk 2.5.4
  Fetching concurrent-ruby 1.1.10
  Installing zeitwerk 2.5.4
  Installing minitest 5.15.0
  Fetching builder 3.2.4
  Fetching erubi 1.10.0
  Installing concurrent-ruby 1.1.10
  Installing builder 3.2.4
  Installing erubi 1.10.0
  Fetching mini_portile2 2.8.0
  Fetching racc 1.6.0
  Installing mini_portile2 2.8.0
  Installing racc 1.6.0 with native extensions
  Fetching crass 1.0.6
  Installing crass 1.0.6
  Installing Ascii85 1.1.0
  Fetching rack 2.2.3
  Fetching nio4r 2.5.8
  Fetching websocket-extensions 0.1.5
  Installing websocket-extensions 0.1.5
  Installing rack 2.2.3
  Installing nio4r 2.5.8 with native extensions
  Fetching marcel 1.0.2
  Installing marcel 1.0.2
  Fetching mini_mime 1.1.2
  Fetching ruby2_keywords 0.0.5
  Installing ruby2_keywords 0.0.5
  Fetching formtastic_i18n 0.6.0
  Installing mini_mime 1.1.2
  Installing formtastic_i18n 0.6.0
  Fetching method_source 1.0.0
  Fetching thor 1.2.1
  Installing method_source 1.0.0
  Installing thor 1.2.1
  Fetching kaminari-core 1.2.2
  Fetching select2-rails 4.0.13
  Installing kaminari-core 1.2.2
  Installing select2-rails 4.0.13
  Fetching public_suffix 4.0.7
  Installing public_suffix 4.0.7
  Fetching afm 0.2.2
  Fetching ruby-next-core 0.14.1
  Installing afm 0.2.2
  Fetching ast 2.4.2
  Installing ast 2.4.2
  Fetching aws-eventstream 1.1.1
  Installing ruby-next-core 0.14.1
  Fetching aws-partitions 1.445.0
  Installing aws-eventstream 1.1.1
  Fetching jmespath 1.4.0
  Installing aws-partitions 1.445.0
  Fetching backport 1.1.2
  Installing jmespath 1.4.0
  Installing backport 1.1.2
  Fetching barby 0.6.8
  Fetching bases 1.0.2
  Fetching bcrypt 3.1.17
  Using benchmark 0.1.1
  Fetching benchmark-ips 2.9.3
  Installing bases 1.0.2
  Installing barby 0.6.8
  Installing bcrypt 3.1.17 with native extensions
  Installing benchmark-ips 2.9.3
  Fetching coderay 1.1.3
  Fetching debug_inspector 1.1.0
  Installing debug_inspector 1.1.0 with native extensions
  Installing coderay 1.1.3
  Fetching msgpack 1.4.5
  Fetching browser_sniffer 1.4.0
  Installing browser_sniffer 1.4.0
  Installing msgpack 1.4.5 with native extensions
  Fetching uniform_notifier 1.14.2
  Using bundler 2.2.32
  Fetching byebug 11.1.3
  Installing uniform_notifier 1.14.2
  Installing byebug 11.1.3 with native extensions
  Fetching nilio 1.0.0
  Installing nilio 1.0.0
  Fetching matrix 0.4.2
  Installing matrix 0.4.2
  Fetching regexp_parser 2.2.1
  Fetching htmlentities 4.3.4
  Installing regexp_parser 2.2.1
  Installing htmlentities 4.3.4
  Fetching rubyzip 2.3.2
  Installing rubyzip 2.3.2
  Fetching chunky_png 1.4.0
  Fetching ruby-rc4 0.1.5
  Installing ruby-rc4 0.1.5
  Fetching connection_pool 2.2.5
  Fetching content_disposition 1.0.0
  Fetching i18n_data 0.11.0
  Installing connection_pool 2.2.5
  Installing chunky_png 1.4.0
  Installing content_disposition 1.0.0
  Fetching sixarm_ruby_unaccent 1.2.0
  Fetching unicode_utils 1.4.0
  Installing i18n_data 0.11.0
  Installing sixarm_ruby_unaccent 1.2.0
  Installing unicode_utils 1.4.0
  Fetching rexml 3.2.5
  Installing rexml 3.2.5
  Fetching multi_json 1.15.0
  Fetching dalli 2.7.11
  Installing multi_json 1.15.0
  Fetching database_cleaner-core 2.0.1
  Fetching dead_end 1.1.7
  Installing dalli 2.7.11
  Installing dead_end 1.1.7
  Installing database_cleaner-core 2.0.1
  Fetching ffi 1.15.5
  Fetching memory_profiler 1.0.0
  Fetching mini_histogram 0.3.1
  Installing memory_profiler 1.0.0
  Fetching ruby-statistics 2.1.3
  Installing mini_histogram 0.3.1
  Fetching orm_adapter 0.5.0
  Installing ruby-statistics 2.1.3
  Fetching diff-lcs 1.4.4
  Installing orm_adapter 0.5.0
  Installing diff-lcs 1.4.4
  Installing ffi 1.15.5 with native extensions
  Fetching docile 1.4.0
  Installing docile 1.4.0
  Fetching unf_ext 0.0.8.1
  Fetching dotenv 2.7.6
  Fetching dry-inflector 0.2.1
  Installing dotenv 2.7.6
  Installing unf_ext 0.0.8.1 with native extensions
  Installing dry-inflector 0.2.1
  Fetching e2mmap 0.1.0
  Installing e2mmap 0.1.0
  Fetching easypost 4.3.0
  Fetching faraday-net_http 2.0.2
  Installing easypost 4.3.0
  Installing faraday-net_http 2.0.2
  Fetching flag_shih_tzu 0.3.23
  Fetching flipper 0.23.1
  Installing flag_shih_tzu 0.3.23
  Installing flipper 0.23.1
  Fetching formatador 0.2.5
  Installing formatador 0.2.5
  Fetching raabro 1.4.0
  Installing raabro 1.4.0
  Fetching geocoder 1.7.5
  Fetching jsonapi-renderer 0.2.2
  Installing jsonapi-renderer 0.2.2
  Installing geocoder 1.7.5
  Fetching rspec-support 3.10.3
  Installing rspec-support 3.10.3
  Fetching graphql 1.13.11
  Fetching rb-fsevent 0.10.4
  Installing rb-fsevent 0.10.4
  Fetching lumberjack 1.2.8
  Installing graphql 1.13.11
  Fetching nenv 0.3.0
  Installing lumberjack 1.2.8
  Installing nenv 0.3.0
  Fetching shellany 0.0.1
  Fetching guard-compat 1.2.1
  Installing shellany 0.0.1
  Installing guard-compat 1.2.1
  Fetching hashdiff 1.0.1
  Fetching hashery 2.1.2
  Installing hashdiff 1.0.1
  Fetching hashie 5.0.0
  Installing hashery 2.1.2
  Installing hashie 5.0.0
  Fetching hiredis 0.6.3
  Fetching http-form_data 2.3.0
  Fetching mime-types-data 3.2021.1115
  Installing hiredis 0.6.3 with native extensions
  Installing http-form_data 2.3.0
  Fetching multi_xml 0.6.0
  Installing mime-types-data 3.2021.1115
  Installing multi_xml 0.6.0
  Fetching rainbow 3.0.0
  Fetching mini_magick 4.11.0
  Installing rainbow 3.0.0
  Fetching interception 0.5
  Installing mini_magick 4.11.0
  Installing interception 0.5 with native extensions
  Fetching phonelib 0.6.58
  Fetching jaro_winkler 1.5.4
  Using json 2.5.1
  Fetching jwt 2.3.0
  Fetching knapsack 1.21.1
  Installing jaro_winkler 1.5.4 with native extensions
  Installing jwt 2.3.0
  Installing knapsack 1.21.1
  Fetching liquid 4.0.3
  Installing phonelib 0.6.58
  Installing liquid 4.0.3
  Fetching lockbox 0.6.8
  Fetching mjml-rails 4.3.2
  Installing lockbox 0.6.8
  Fetching parallel 1.21.0
  Installing mjml-rails 4.3.2
  Fetching pdf-core 0.9.0
  Installing parallel 1.21.0
  Fetching ttfunk 1.7.0
  Installing ttfunk 1.7.0
  Fetching pg 1.2.3
  Installing pdf-core 0.9.0
  Fetching redis 4.5.1
  Installing pg 1.2.3 with native extensions
  Fetching ruby-progressbar 1.11.0
  Installing redis 4.5.1
  Installing ruby-progressbar 1.11.0
  Fetching unicode-display_width 2.1.0
  Fetching tilt 2.0.10
  Installing unicode-display_width 2.1.0
  Installing tilt 2.0.10
  Fetching simplecov-html 0.12.3
  Fetching simplecov_json_formatter 0.1.4
  Installing simplecov_json_formatter 0.1.4
  Fetching slack-notifier 2.4.0
  Fetching webrick 1.7.0
  Installing slack-notifier 2.4.0
  Installing webrick 1.7.0
  Installing simplecov-html 0.12.3
  Fetching spring 2.1.1
  Installing spring 2.1.1
  Fetching stackprof 0.2.19
  Installing stackprof 0.2.19 with native extensions
  Fetching stateful_enum 0.6.0
  Fetching stripe 6.2.0
  Installing stateful_enum 0.6.0
  Fetching test-prof 1.0.8
  Installing stripe 6.2.0
  Installing test-prof 1.0.8
  Fetching timecop 0.9.5
  Installing timecop 0.9.5
  Fetching vandal_ui 0.4.5
  Fetching vcr 6.0.0
  Installing vcr 6.0.0
  Fetching wkhtmltopdf-binary 0.12.6.5
  Fetching wkhtmltopdf-heroku 2.12.6.0
  Installing vandal_ui 0.4.5
  Fetching i18n 1.10.0
  Took  55.02 seconds
Error: Error: The process '/opt/hostedtoolcache/Ruby/3.0.3/x64/bin/bundle' failed with exit code null
    at ExecState._setResult (/root/actions-runner/_work/_actions/ruby/setup-ruby/v1/dist/index.js:4918:25)
    at ExecState.CheckComplete (/root/actions-runner/_work/_actions/ruby/setup-ruby/v1/dist/index.js:4901:18)
    at ChildProcess.<anonymous> (/root/actions-runner/_work/_actions/ruby/setup-ruby/v1/dist/index.js:4795:27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:[68](https://github.com/PostCo/project-tapir/runs/7075602949?check_suite_focus=true#step:11:74)7:12)
```

**Comment by eregon** [comment]
You'll need to debug this yourself, nothing I can do to help here, besides saying try running the same command manually on your self-hosted runner, or as a separate step in your workflow without `bundler-cache: true`.

Also note:
> Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.

**Comment by andychongyz** [comment]
> You'll need to debug this yourself, nothing I can do to help here, besides saying try running the same command manually on your self-hosted runner, or as a separate step in your workflow without `bundler-cache: true`.
> 
> Also note:
> 
> > Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.

@eregon I remove the `sudo` usage. But, what is the `same command` you mention, I'm trying to debug it by running it manually in my self-hosted instance.

**Comment by andychongyz** [comment]
@eregon Thanks a lot, turns out it is because the runner is out of memory, adding swap solves the problem.
