### ISSUE TITLE
OpenSSL is not available

### ISSUE THREAD

**Issue by n1xn** [ruby/setup-ruby#416]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
on: push

jobs:
  linters:
    name: Linters & Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Node Packages
        run: npm install

      - name: Run Prettier
        run: npx prettier --check
```

### Link to the log of a failed workflow job, or to a gist with the output

https://pastebin.com/44wJwn5j

### The command and output of the failing step

```shell
MacBook-Pro:project dev$ act
[quality.yml/Linters & Style] 🚀  Start image=catthehacker/ubuntu:act-latest
[quality.yml/Linters & Style]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=false
[quality.yml/Linters & Style]   🐳  docker create image=catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[quality.yml/Linters & Style]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[quality.yml/Linters & Style]   ☁  git clone 'https://github.com/ruby/setup-ruby' # ref=v1
[quality.yml/Linters & Style]   ☁  git clone 'https://github.com/actions/setup-node' # ref=v3
[quality.yml/Linters & Style] ⭐ Run Main Checkout
[quality.yml/Linters & Style]   🐳  docker cp src=/Users/dev/Desktop/GITHUB/project/. dst=/Users/dev/Desktop/GITHUB/project
[quality.yml/Linters & Style]   ✅  Success - Main Checkout
[quality.yml/Linters & Style] ⭐ Run Main Setup Ruby
[quality.yml/Linters & Style]   🐳  docker cp src=/Users/dev/.cache/act/ruby-setup-ruby@v1/ dst=/var/run/act/actions/ruby-setup-ruby@v1/
[quality.yml/Linters & Style]   🐳  docker exec cmd=[node /var/run/act/actions/ruby-setup-ruby@v1/dist/index.js] user= workdir=
| Using 3.1.2 as input from file .ruby-version
[quality.yml/Linters & Style]   💬  ::debug::isExplicit: 3.1.2
[quality.yml/Linters & Style]   💬  ::debug::explicit? true
[quality.yml/Linters & Style]   💬  ::debug::checking cache: /opt/hostedtoolcache/Ruby/3.1.2/x64
[quality.yml/Linters & Style]   💬  ::debug::not found
[quality.yml/Linters & Style]   ❓  ::group::Modifying PATH
| Entries added to PATH to use selected Ruby:
|   /opt/hostedtoolcache/Ruby/3.1.2/x64/bin
[quality.yml/Linters & Style]   ❓  ::endgroup::
[quality.yml/Linters & Style]   ❓  ::group::Downloading Ruby
| https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-3.1.2-ubuntu-20.04.tar.gz
[quality.yml/Linters & Style]   💬  ::debug::Downloading https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-3.1.2-ubuntu-20.04.tar.gz
[quality.yml/Linters & Style]   💬  ::debug::Destination /tmp/23d582a3-cf90-425c-96a7-617ed23b6e65
[quality.yml/Linters & Style]   💬  ::debug::download complete
| Took   9.83 seconds
[quality.yml/Linters & Style]   ❓  ::endgroup::
[quality.yml/Linters & Style]   ❓  ::group::Extracting  Ruby
| [command]/usr/bin/tar -xz -C /opt/hostedtoolcache/Ruby/3.1.2 -f /tmp/23d582a3-cf90-425c-96a7-617ed23b6e65
| Took   0.66 seconds
[quality.yml/Linters & Style]   ❓  ::endgroup::
[quality.yml/Linters & Style]   ❓  ::group::Print Ruby version
| [command]/opt/hostedtoolcache/Ruby/3.1.2/x64/bin/ruby --version
| ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
| Took   0.03 seconds
[quality.yml/Linters & Style]   ❓  ::endgroup::
[quality.yml/Linters & Style]   ❓  ::group::Installing Bundler
| Using Bundler 2.3.7 from Gemfile.lock BUNDLED WITH 2.3.7
| [command]/opt/hostedtoolcache/Ruby/3.1.2/x64/bin/gem install bundler -v 2.3.7
| ERROR:  While executing gem ... (Gem::Exception)
|     OpenSSL is not available. Install OpenSSL and rebuild Ruby (preferred) or use non-HTTPS sources
| Took   0.38 seconds
[quality.yml/Linters & Style]   ❓  ::endgroup::
[quality.yml/Linters & Style]   ❗  ::error::Error: The process '/opt/hostedtoolcache/Ruby/3.1.2/x64/bin/gem' failed with exit code 1%0A    at ExecState._setResult (/run/act/actions/ruby-setup-ruby@v1/dist/index.js:5340:25)%0A    at ExecState.CheckComplete (/run/act/actions/ruby-setup-ruby@v1/dist/index.js:5323:18)%0A    at ChildProcess.<anonymous> (/run/act/actions/ruby-setup-ruby@v1/dist/index.js:5217:27)%0A    at ChildProcess.emit (node:events:513:28)%0A    at maybeClose (node:internal/child_process:1100:16)%0A    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
[quality.yml/Linters & Style]   ❌  Failure - Main Setup Ruby
[quality.yml/Linters & Style] exitcode '1': failure
[quality.yml/Linters & Style] 🏁  Job failed
Error: Job 'Linters & Style' failed
```

### Any other notes?

Tested workflow locally with `act` on MacOS

**Comment by hsbt** [comment]
Does it reproduce in GitHub Actions? It seems act environment, not GitHub actions.

**Comment by MSP-Greg** [comment]
I'm not going to check the docker file, but please see the README section about self-hosted runners.  There is an ENV variable 'ImageOS'.  For Ubuntu-22.04, it's `ubuntu22`, for 20.04, it's `ubuntu20`.  Those two versions of Ubuntu have different (and incompatible) versions of OpenSSL installed.

The log from above is loading a Ruby built for Ubuntu 20.04.  If your image is Ubuntu 22.04, Ruby's OpenSSL won't work.

**Comment by eregon** [comment]
User error, bad report, this is not running on GitHub-hosted runners.

**Comment by ZilvinasKucinskas** [comment]
@n1xn Have you found a way to solve the `OpenSSL` problem with the `act` runner?

**Comment by matoni109** [comment]
@n1xn I'm also having this issue
