### ISSUE TITLE
Please add support for JRuby 9.3.12.0, 9.3.13.0, and 9.4.5.0

### ISSUE THREAD

**Issue by jbaiza** [ruby/setup-ruby#544]
An error is returned when JRuby 9.3.13.0 is used:
```
Error: Unknown version 9.3.13.0 for jruby on ubuntu-22.04
        available versions for jruby on ubuntu-22.04: 9.1.17.0, 9.2.9.0, 9.2.10.0, 9.2.11.0, 9.2.11.1, 9.2.12.0, 9.2.13.0, 9.2.14.0, 9.2.15.0, 9.2.16.0, 9.2.17.0, 9.2.18.0, 9.2.19.0, 9.2.20.0, 9.2.20.1, 9.2.21.0, 9.3.0.0, 9.3.1.0, 9.3.2.0, 9.3.3.0, 9.3.4.0, 9.3.6.0, 9.3.7.0, 9.3.8.0, 9.3.9.0, 9.3.10.0, 9.3.11.0, 9.4.0.0, 9.4.1.0, 9.4.2.0, 9.4.3.0, 9.4.4.0, head
```
We are using recommended `uses: ruby/setup-ruby@v1`.

**Comment by dentarg** [comment]
It was very [recently released](https://www.jruby.org/2023/11/02/jruby-9-3-13-0), we need https://github.com/rbenv/ruby-build/pull/2289 to be merged and then the automation https://github.com/ruby/ruby-builder/blob/master/.github/workflows/check-new-releases.yml to run

**Comment by rsim** [comment]
@dentarg https://github.com/rbenv/ruby-build/pull/2289 is now merged but the ruby-builder automation https://github.com/ruby/ruby-builder/actions/runs/6763182999/job/18380007387 failed with
```
New releases for jruby: ["9.3.13.0", "9.4.5.0"]
ruby build.rb jruby-9.3.13.0 jruby-9.4.[5](https://github.com/ruby/ruby-builder/actions/runs/6763182999/job/18380007387#step:8:6).0
build.rb:24:in `<main>': More than 1 version not supported for JRuby (RuntimeError)
check-new-releases.rb:13:in `sh': ["ruby", "build.rb", "jruby-9.3.13.0", "jruby-9.4.5.0"] failed (RuntimeError)
	from check-new-releases.rb:53:in `block in <main>'
	from check-new-releases.rb:34:in `each_pair'
	from check-new-releases.rb:34:in `<main>'
Error: Process completed with exit code 1.
```

**Comment by dentarg** [comment]
Then we wait for maintainers to add it manually, maybe possible to help them with PRs to the builder repo and here.

**Comment by rsim** [comment]
https://github.com/ruby/ruby-builder/ README says "Please report issues to ruby/setup-ruby" which is here 🙂 Are you the same maintainers' team or not? It was not clear to me where to report this automation failure...

As I see @eregon added this commit https://github.com/ruby/ruby-builder/commit/79d26f098861635393a838e557e51b0c633d9d3c that does not allow to build several JRuby versions at once. It is not quite clear why it was added. If there are some limitations why it can't be done then probably in https://github.com/ruby/ruby-builder/blob/master/check-new-releases.rb#L53
```ruby
sh("ruby", "build.rb", *new.map { |v| "#{engine}-#{v}" })
```
should be changed to
```ruby
if engine == 'jruby'
  new.each do |v|
    sh("ruby", "build.rb", "#{engine}-#{v}")
  end
else
  sh("ruby", "build.rb", *new.map { |v| "#{engine}-#{v}" })
end
```

**Comment by dentarg** [comment]
No, I'm not maintainer

**Comment by eregon** [comment]
Added in https://github.com/ruby/setup-ruby/releases/tag/v1.160.0
