### ISSUE TITLE
Ruby 2.7 LoadError

### ISSUE THREAD

**Issue by JuanitoFatas** [ruby/setup-ruby#95]
Sorry I know this is not the right project to open this issue, sorry in advance.

Wonder if you got any pointers on resolving [this `LoadError`](https://github.com/ruby/www.ruby-lang.org/runs/1288399116) for ruby/www.ruby-lang.org from [this PR](https://github.com/ruby/www.ruby-lang.org/pull/2518) - The PR itself is irrelevant. 

The [action workflow file](https://github.com/ruby/www.ruby-lang.org/blob/master/.github/workflows/ci.yml).

<details>
<summary>Full Error</summary>

```
Checking markdown files... ok
rake aborted!
LoadError: dlopen(/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/ffi-1.11.1/lib/ffi_c.bundle, 9): Library not loaded: /Users/runner/.rubies/ruby-2.7.1/lib/libruby.2.7.dylib
  Referenced from: /Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/ffi-1.11.1/lib/ffi_c.bundle
  Reason: image not found - /Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/ffi-1.11.1/lib/ffi_c.bundle
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/ffi-1.11.1/lib/ffi.rb:6:in `require'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/ffi-1.11.1/lib/ffi.rb:6:in `rescue in <top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/ffi-1.11.1/lib/ffi.rb:3:in `<top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/sassc-2.2.1/lib/sassc/native.rb:3:in `require'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/sassc-2.2.1/lib/sassc/native.rb:3:in `<top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/sassc-2.2.1/lib/sassc.rb:31:in `require_relative'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/sassc-2.2.1/lib/sassc.rb:31:in `<top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.0.1/lib/jekyll/converters/scss.rb:3:in `require'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.0.1/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.0.1/lib/jekyll-sass-converter.rb:4:in `require'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.0.1/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll.rb:206:in `require'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll.rb:206:in `<top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/lanyon-0.4.1/lib/lanyon.rb:7:in `require'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/lanyon-0.4.1/lib/lanyon.rb:7:in `<top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/Rakefile:21:in `require'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/Rakefile:21:in `block in <top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
/Users/runner/.rubies/ruby-2.7.2/bin/bundle:23:in `load'
/Users/runner/.rubies/ruby-2.7.2/bin/bundle:23:in `<main>'

Caused by:
LoadError: cannot load such file -- 2.7/ffi_c
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/ffi-1.11.1/lib/ffi.rb:4:in `require'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/ffi-1.11.1/lib/ffi.rb:4:in `<top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/sassc-2.2.1/lib/sassc/native.rb:3:in `require'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/sassc-2.2.1/lib/sassc/native.rb:3:in `<top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/sassc-2.2.1/lib/sassc.rb:31:in `require_relative'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/sassc-2.2.1/lib/sassc.rb:31:in `<top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.0.1/lib/jekyll/converters/scss.rb:3:in `require'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.0.1/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.0.1/lib/jekyll-sass-converter.rb:4:in `require'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.0.1/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll.rb:206:in `require'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll.rb:206:in `<top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/lanyon-0.4.1/lib/lanyon.rb:7:in `require'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/lanyon-0.4.1/lib/lanyon.rb:7:in `<top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/Rakefile:21:in `require'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/Rakefile:21:in `block in <top (required)>'
/Users/runner/work/www.ruby-lang.org/www.ruby-lang.org/vendor/bundle/ruby/2.7.0/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
/Users/runner/.rubies/ruby-2.7.2/bin/bundle:23:in `load'
/Users/runner/.rubies/ruby-2.7.2/bin/bundle:23:in `<main>'
Tasks: TOP => test => build
(See full trace by running task with --trace)
Error: Process completed with exit code 1.
```
</details>

It started [breaking since October 6](https://github.com/ruby/www.ruby-lang.org/commits/master).

Cheers.

**Comment by eregon** [comment]
You are manually caching `bundle install`, that's tricky to do correctly.
Could you try with https://github.com/ruby/setup-ruby#caching-bundle-install-automatically and remove anything related to caching or Bundler in the workflow?

You can also try changing the key for `actions/cache@v1` (by appending some random string), to invalidate the cache, and see if this is caused by cached data.

BTW, there is warning, probably harmless but seems worth fixing:
https://github.com/ruby/www.ruby-lang.org/runs/1288399116#step:4:1

**Comment by eregon** [comment]
The `$CUSTOM_RUBY_VERSION` logic might also cause issues. Why not simply using `ruby RUBY_VERSION` in the Gemfile?

I don't recall anymore if in Bundler `ruby version` in the `Gemfile` has any effect. Maybe it's not necessary anymore?

**Comment by JuanitoFatas** [comment]
@eregon Thanks Benoit! I have fixed the build based on your recommendation. You are amazing! 

https://github.com/ruby/www.ruby-lang.org/pull/2521
